services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behavioral-widget
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    networks:
      - behavioral-widget
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    container_name: behavioral-widget-postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - behavioral-widget

volumes:
  pgdata:

networks:
  behavioral-widget:
    driver: bridge
