services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behavioral-widget
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    networks:
      - behavioral-widget
    stdin_open: true
    tty: true

networks:
  behavioral-widget:
    driver: bridge
